// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package model

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type projectEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var ProjectEntityBinding = projectEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 1994687443603552166,
}

// ProjectEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var ProjectEntity_ = struct {
	Id                 *objectbox.PropertyUint64
	Name               *objectbox.PropertyString
	Info               *objectbox.PropertyString
	Interval           *objectbox.PropertyInt32
	CreatedAt          *objectbox.PropertyInt64
	ShootingDays       *objectbox.PropertyFloat32
	TotalVideoLength   *objectbox.PropertyFloat32
	PreviewVideoLength *objectbox.PropertyFloat32
	CameraSettings     *objectbox.PropertyByteVector
	VideoFPS           *objectbox.PropertyInt32
	VideoMaxImage      *objectbox.PropertyInt32
	VideoFrameCount    *objectbox.PropertyInt
	ImageCount         *objectbox.PropertyInt
	LatestImageName    *objectbox.PropertyString
	StartedAt          *objectbox.PropertyInt64
	EndedAt            *objectbox.PropertyInt64
	UpdateAt           *objectbox.PropertyInt64
	Enable             *objectbox.PropertyBool
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	Info: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	Interval: &objectbox.PropertyInt32{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	ShootingDays: &objectbox.PropertyFloat32{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	TotalVideoLength: &objectbox.PropertyFloat32{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	PreviewVideoLength: &objectbox.PropertyFloat32{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	CameraSettings: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	VideoFPS: &objectbox.PropertyInt32{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	VideoMaxImage: &objectbox.PropertyInt32{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	VideoFrameCount: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	ImageCount: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     18,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	LatestImageName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     19,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	StartedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     20,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	EndedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     21,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	UpdateAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     22,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
	Enable: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     23,
			Entity: &ProjectEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (projectEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (projectEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("ProjectEntity", 1, 1994687443603552166)
	model.Property("Id", 6, 1, 6994982235533928328)
	model.PropertyFlags(1)
	model.Property("Name", 9, 2, 1610079536195358594)
	model.PropertyFlags(2080)
	model.PropertyIndex(1, 6941035266594143747)
	model.Property("Info", 9, 3, 547217713188363363)
	model.Property("Interval", 5, 4, 987833402084319865)
	model.Property("CreatedAt", 10, 7, 2752261256299973186)
	model.Property("ShootingDays", 7, 10, 4249619312989082471)
	model.Property("TotalVideoLength", 7, 11, 535436702901036224)
	model.Property("PreviewVideoLength", 7, 12, 4757757768936413671)
	model.Property("CameraSettings", 23, 13, 6091359989813993846)
	model.Property("VideoFPS", 5, 14, 5766839287658650703)
	model.Property("VideoMaxImage", 5, 15, 8260402102223984509)
	model.Property("VideoFrameCount", 6, 16, 4959251309210067918)
	model.Property("ImageCount", 6, 18, 8524371154695624402)
	model.Property("LatestImageName", 9, 19, 2627974856941245340)
	model.Property("StartedAt", 10, 20, 2719703509981112629)
	model.Property("EndedAt", 10, 21, 7473525894695439415)
	model.Property("UpdateAt", 10, 22, 4818775003864243292)
	model.Property("Enable", 1, 23, 6811454939483702910)
	model.EntityLastPropertyId(23, 6811454939483702910)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (projectEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*ProjectEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (projectEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*ProjectEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (projectEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (projectEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*ProjectEntity)
	var propCreatedAt int64
	{
		var err error
		propCreatedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.CreatedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on ProjectEntity.CreatedAt: " + err.Error())
		}
	}

	var propCameraSettings []byte
	{
		var err error
		propCameraSettings, err = CameraSettingsConvToDatabaseValue(obj.CameraSettings)
		if err != nil {
			return errors.New("converter CameraSettingsConvToDatabaseValue() failed on ProjectEntity.CameraSettings: " + err.Error())
		}
	}

	var propStartedAt int64
	{
		var err error
		propStartedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.StartedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on ProjectEntity.StartedAt: " + err.Error())
		}
	}

	var propEndedAt int64
	{
		var err error
		propEndedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.EndedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on ProjectEntity.EndedAt: " + err.Error())
		}
	}

	var propUpdateAt int64
	{
		var err error
		propUpdateAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.UpdateAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on ProjectEntity.UpdateAt: " + err.Error())
		}
	}

	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetInfo = fbutils.CreateStringOffset(fbb, obj.Info)
	var offsetCameraSettings = fbutils.CreateByteVectorOffset(fbb, propCameraSettings)
	var offsetLatestImageName = fbutils.CreateStringOffset(fbb, obj.LatestImageName)

	// build the FlatBuffers object
	fbb.StartObject(23)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetInfo)
	fbutils.SetInt32Slot(fbb, 3, obj.Interval)
	fbutils.SetBoolSlot(fbb, 22, obj.Enable)
	fbutils.SetInt32Slot(fbb, 13, obj.VideoFPS)
	fbutils.SetInt32Slot(fbb, 14, obj.VideoMaxImage)
	fbutils.SetFloat32Slot(fbb, 9, obj.ShootingDays)
	fbutils.SetFloat32Slot(fbb, 10, obj.TotalVideoLength)
	fbutils.SetFloat32Slot(fbb, 11, obj.PreviewVideoLength)
	fbutils.SetInt64Slot(fbb, 15, int64(obj.VideoFrameCount))
	fbutils.SetUOffsetTSlot(fbb, 12, offsetCameraSettings)
	fbutils.SetInt64Slot(fbb, 17, int64(obj.ImageCount))
	fbutils.SetUOffsetTSlot(fbb, 18, offsetLatestImageName)
	fbutils.SetInt64Slot(fbb, 19, propStartedAt)
	fbutils.SetInt64Slot(fbb, 20, propEndedAt)
	fbutils.SetInt64Slot(fbb, 21, propUpdateAt)
	fbutils.SetInt64Slot(fbb, 6, propCreatedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (projectEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'ProjectEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	propCreatedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 16))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on ProjectEntity.CreatedAt: " + err.Error())
	}

	propCameraSettings, err := CameraSettingsConvToEntityProperty(fbutils.GetByteVectorSlot(table, 28))
	if err != nil {
		return nil, errors.New("converter CameraSettingsConvToEntityProperty() failed on ProjectEntity.CameraSettings: " + err.Error())
	}

	propStartedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 42))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on ProjectEntity.StartedAt: " + err.Error())
	}

	propEndedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 44))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on ProjectEntity.EndedAt: " + err.Error())
	}

	propUpdateAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 46))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on ProjectEntity.UpdateAt: " + err.Error())
	}

	return &ProjectEntity{
		Id:                 propId,
		Name:               fbutils.GetStringSlot(table, 6),
		Info:               fbutils.GetStringSlot(table, 8),
		Interval:           fbutils.GetInt32Slot(table, 10),
		Enable:             fbutils.GetBoolSlot(table, 48),
		VideoFPS:           fbutils.GetInt32Slot(table, 30),
		VideoMaxImage:      fbutils.GetInt32Slot(table, 32),
		ShootingDays:       fbutils.GetFloat32Slot(table, 22),
		TotalVideoLength:   fbutils.GetFloat32Slot(table, 24),
		PreviewVideoLength: fbutils.GetFloat32Slot(table, 26),
		VideoFrameCount:    fbutils.GetIntSlot(table, 34),
		CameraSettings:     propCameraSettings,
		ImageCount:         fbutils.GetIntSlot(table, 38),
		LatestImageName:    fbutils.GetStringSlot(table, 40),
		StartedAt:          propStartedAt,
		EndedAt:            propEndedAt,
		UpdateAt:           propUpdateAt,
		CreatedAt:          propCreatedAt,
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (projectEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*ProjectEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (projectEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*ProjectEntity), nil)
	}
	return append(slice.([]*ProjectEntity), object.(*ProjectEntity))
}

// Box provides CRUD access to ProjectEntity objects
type ProjectEntityBox struct {
	*objectbox.Box
}

// BoxForProjectEntity opens a box of ProjectEntity objects
func BoxForProjectEntity(ob *objectbox.ObjectBox) *ProjectEntityBox {
	return &ProjectEntityBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the ProjectEntity.Id property on the passed object will be assigned the new ID as well.
func (box *ProjectEntityBox) Put(object *ProjectEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the ProjectEntity.Id property on the passed object will be assigned the new ID as well.
func (box *ProjectEntityBox) Insert(object *ProjectEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *ProjectEntityBox) Update(object *ProjectEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *ProjectEntityBox) PutAsync(object *ProjectEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the ProjectEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the ProjectEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *ProjectEntityBox) PutMany(objects []*ProjectEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *ProjectEntityBox) Get(id uint64) (*ProjectEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*ProjectEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *ProjectEntityBox) GetMany(ids ...uint64) ([]*ProjectEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*ProjectEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *ProjectEntityBox) GetManyExisting(ids ...uint64) ([]*ProjectEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*ProjectEntity), nil
}

// GetAll reads all stored objects
func (box *ProjectEntityBox) GetAll() ([]*ProjectEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*ProjectEntity), nil
}

// Remove deletes a single object
func (box *ProjectEntityBox) Remove(object *ProjectEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *ProjectEntityBox) RemoveMany(objects ...*ProjectEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the ProjectEntity_ struct to create conditions.
// Keep the *ProjectEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *ProjectEntityBox) Query(conditions ...objectbox.Condition) *ProjectEntityQuery {
	return &ProjectEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the ProjectEntity_ struct to create conditions.
// Keep the *ProjectEntityQuery if you intend to execute the query multiple times.
func (box *ProjectEntityBox) QueryOrError(conditions ...objectbox.Condition) (*ProjectEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &ProjectEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See ProjectEntityAsyncBox for more information.
func (box *ProjectEntityBox) Async() *ProjectEntityAsyncBox {
	return &ProjectEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// ProjectEntityAsyncBox provides asynchronous operations on ProjectEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type ProjectEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForProjectEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use ProjectEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForProjectEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *ProjectEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &ProjectEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *ProjectEntityAsyncBox) Put(object *ProjectEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *ProjectEntityAsyncBox) Insert(object *ProjectEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *ProjectEntityAsyncBox) Update(object *ProjectEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *ProjectEntityAsyncBox) Remove(object *ProjectEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all ProjectEntity which Id is either 42 or 47:
//
// box.Query(ProjectEntity_.Id.In(42, 47)).Find()
type ProjectEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *ProjectEntityQuery) Find() ([]*ProjectEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*ProjectEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *ProjectEntityQuery) Offset(offset uint64) *ProjectEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *ProjectEntityQuery) Limit(limit uint64) *ProjectEntityQuery {
	query.Query.Limit(limit)
	return query
}

type lastRunningEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var LastRunningEntityBinding = lastRunningEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 8518891464527168988,
}

// LastRunningEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var LastRunningEntity_ = struct {
	Id          *objectbox.PropertyUint64
	ProjectName *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &LastRunningEntityBinding.Entity,
		},
	},
	ProjectName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &LastRunningEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (lastRunningEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (lastRunningEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("LastRunningEntity", 2, 8518891464527168988)
	model.Property("Id", 6, 1, 3440860295687353952)
	model.PropertyFlags(1)
	model.Property("ProjectName", 9, 2, 1004966284019481542)
	model.EntityLastPropertyId(2, 1004966284019481542)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (lastRunningEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*LastRunningEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (lastRunningEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*LastRunningEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (lastRunningEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (lastRunningEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*LastRunningEntity)
	var offsetProjectName = fbutils.CreateStringOffset(fbb, obj.ProjectName)

	// build the FlatBuffers object
	fbb.StartObject(2)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetProjectName)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (lastRunningEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'LastRunningEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &LastRunningEntity{
		Id:          propId,
		ProjectName: fbutils.GetStringSlot(table, 6),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (lastRunningEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*LastRunningEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (lastRunningEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*LastRunningEntity), nil)
	}
	return append(slice.([]*LastRunningEntity), object.(*LastRunningEntity))
}

// Box provides CRUD access to LastRunningEntity objects
type LastRunningEntityBox struct {
	*objectbox.Box
}

// BoxForLastRunningEntity opens a box of LastRunningEntity objects
func BoxForLastRunningEntity(ob *objectbox.ObjectBox) *LastRunningEntityBox {
	return &LastRunningEntityBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the LastRunningEntity.Id property on the passed object will be assigned the new ID as well.
func (box *LastRunningEntityBox) Put(object *LastRunningEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the LastRunningEntity.Id property on the passed object will be assigned the new ID as well.
func (box *LastRunningEntityBox) Insert(object *LastRunningEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *LastRunningEntityBox) Update(object *LastRunningEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *LastRunningEntityBox) PutAsync(object *LastRunningEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the LastRunningEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the LastRunningEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *LastRunningEntityBox) PutMany(objects []*LastRunningEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *LastRunningEntityBox) Get(id uint64) (*LastRunningEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*LastRunningEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *LastRunningEntityBox) GetMany(ids ...uint64) ([]*LastRunningEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*LastRunningEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *LastRunningEntityBox) GetManyExisting(ids ...uint64) ([]*LastRunningEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*LastRunningEntity), nil
}

// GetAll reads all stored objects
func (box *LastRunningEntityBox) GetAll() ([]*LastRunningEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*LastRunningEntity), nil
}

// Remove deletes a single object
func (box *LastRunningEntityBox) Remove(object *LastRunningEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *LastRunningEntityBox) RemoveMany(objects ...*LastRunningEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the LastRunningEntity_ struct to create conditions.
// Keep the *LastRunningEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *LastRunningEntityBox) Query(conditions ...objectbox.Condition) *LastRunningEntityQuery {
	return &LastRunningEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the LastRunningEntity_ struct to create conditions.
// Keep the *LastRunningEntityQuery if you intend to execute the query multiple times.
func (box *LastRunningEntityBox) QueryOrError(conditions ...objectbox.Condition) (*LastRunningEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &LastRunningEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See LastRunningEntityAsyncBox for more information.
func (box *LastRunningEntityBox) Async() *LastRunningEntityAsyncBox {
	return &LastRunningEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// LastRunningEntityAsyncBox provides asynchronous operations on LastRunningEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type LastRunningEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForLastRunningEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use LastRunningEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForLastRunningEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *LastRunningEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &LastRunningEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *LastRunningEntityAsyncBox) Put(object *LastRunningEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *LastRunningEntityAsyncBox) Insert(object *LastRunningEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *LastRunningEntityAsyncBox) Update(object *LastRunningEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *LastRunningEntityAsyncBox) Remove(object *LastRunningEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all LastRunningEntity which Id is either 42 or 47:
//
// box.Query(LastRunningEntity_.Id.In(42, 47)).Find()
type LastRunningEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *LastRunningEntityQuery) Find() ([]*LastRunningEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*LastRunningEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *LastRunningEntityQuery) Offset(offset uint64) *LastRunningEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *LastRunningEntityQuery) Limit(limit uint64) *LastRunningEntityQuery {
	query.Query.Limit(limit)
	return query
}
